- alias: Push notification when the garage door is open
  trigger:
    platform: state
    entity_id: cover.garage_door
    from: closed
    to: open
    for: 0:15:00
  action:
    service: notify.mobile_app_sm_g781v
    data:
      message: The garage has been left open
      data:
        actions:
        - action: close_garage
          title: Close Garage Door
  id: 769638308a0a4973b8930f7a6f2a2693
- alias: Actionable notification - close garage door
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: close_garage
  action:
    service: cover.close_cover
    entity_id: cover.garage_door
    data: {}
  id: c696dd277c6546ecb1f4e0f82052822f
- alias: Close garage door if its open for 15 minutes after 10PM
  trigger:
    platform: state
    entity_id: cover.garage_door
    from: closed
    to: open
    for: 0:15:00
  condition:
    condition: time
    after: '22:00:00'
    before: 05:00:00
  action:
    service: cover.close_cover
    entity_id: cover.garage_door
    data: {}
  id: 6d78a4ce69da44f0ba38ac9241cdc277
- alias: Update Tesla location as MQTT location updates
  initial_state: true
  trigger:
  - platform: mqtt
    topic: teslamate/cars/1/latitude
  - platform: mqtt
    topic: teslamate/cars/1/longitude
  action:
  - service: device_tracker.see
    data_template:
      dev_id: tesla_location
      gps:
      - '{{ states.sensor.tesla_latitude.state }}'
      - '{{ states.sensor.tesla_longitude.state }}'
  id: 77069c1dd26b4913b7fbbb00ae85b688
- alias: Open garage if car returns home
  initial_state: true
  trigger:
  - platform: state
    entity_id: device_tracker.tesla_location
    from: not_home
    to: home
  action:
  - service: cover.open_cover
    entity_id: cover.garage_door
  id: 78aa903d4f1d4085b77726ac84b0faeb
- alias: Close garage if car is away
  initial_state: true
  trigger:
  - platform: state
    entity_id: device_tracker.tesla_location
    from: home
    to: not_home
  action:
  - service: cover.close_cover
    entity_id: cover.garage_door
  id: 3d9513db194f4f44b8310e57949968d1
- alias: Set timer if teslamate reports something is open to alert us
  initial_state: true
  trigger:
  - platform: mqtt
    topic: teslamate/cars/1/windows_open
    payload: 'true'
  - platform: mqtt
    topic: teslamate/cars/1/doors_open
    payload: 'true'
  - platform: mqtt
    topic: teslamate/cars/1/trunk_open
    payload: 'true'
  - platform: mqtt
    topic: teslamate/cars/1/frunk_open
    payload: 'true'
  action:
  - service: script.turn_on
    data_template:
      entity_id: script.notify_tesla_{{trigger.topic.split('/')[3]}}
  id: 97666db34e994b818eaec4d452fd747a
- alias: Cancel notification if said door/window is closed
  initial_state: true
  trigger:
  - platform: mqtt
    topic: teslamate/cars/1/windows_open
    payload: 'false'
  - platform: mqtt
    topic: teslamate/cars/1/doors_open
    payload: 'false'
  - platform: mqtt
    topic: teslamate/cars/1/trunk_open
    payload: 'false'
  - platform: mqtt
    topic: teslamate/cars/1/frunk_open
    payload: 'false'
  action:
  - service: script.turn_off
    data_template:
      entity_id: script.notify_tesla_{{trigger.topic.split('/')[3]}}
  id: c0eaba319f6746dbb5b7a2b3f2ea600c
- id: '1632438333035'
  alias: Tag CarTag is scanned to toggle garage door
  description: ''
  trigger:
  - platform: tag
    tag_id: b9353dee-6334-4bab-8957-9793fff7c3e5
  condition: []
  action:
  - service: cover.toggle
    target:
      entity_id: cover.garage_door
  mode: single
- id: '1632441585625'
  alias: Tag OfficeDeskTag to start timer
  description: ''
  trigger:
  - platform: tag
    tag_id: aa7982d0-2248-4655-9c8f-d987d9e1229f
  condition: []
  action:
  - service: timer.start
    data:
      duration: '0'
    target:
      entity_id: timer.officelight
  mode: single
- id: '1632442918507'
  alias: Tag OfficeDeskTag to finish timer
  description: ''
  trigger:
  - platform: tag
    tag_id: aa7982d0-2248-4655-9c8f-d987d9e1229f
  condition:
  - condition: state
    entity_id: timer.officelight
    state: active
  action:
  - service: timer.finish
    target:
      entity_id: timer.officelight
  mode: single
- id: '1632446126239'
  alias: Office Room Lights
  description: ''
  use_blueprint:
    path: homeassistant/yet_another_motion_light.yaml
    input:
      motion_entity: binary_sensor.office_motionsensor_occupancy
      light_target:
        entity_id: light.office_ceiling_lights
      no_motion_wait: 90
      timer_blocker: timer.officelight
      timer_blocker_boolean: true
- id: '1632446796658'
  alias: Living Room Dine Lights
  description: ''
  use_blueprint:
    path: homeassistant/yet_another_motion_light.yaml
    input:
      motion_entity: binary_sensor.living_motionsensor_occupancy
      light_target:
        entity_id: light.living_room_dining_lights_2
      illuminance_sensor: sensor.living_motionsensor_illuminance_lux
      illuminance_level: 50
