views:
  - title: Home
    icon: mdi:home
    badges: []
    cards:
      - type: custom:button-card
        color_type: icon
        entity: cover.garage_door
        icon: mdi:garage
        name: Garage Door
        size: 100%
        show_state: true
        show_name: false
        state:
          - value: open
            color: var(--color-error)
            icon: mdi:garage-open
            animation: blink 2s ease infinite
          - operator: default
            color: var(--color-green-bright-1)
            icon: mdi:garage
        tap_action:
          action: toggle
        styles:
          card:
            - color: >
                [[[ if (states['cover.garage_door'].state == "open") return
                "var(--color-error)"; else return
                "var(--color-green-bright-1)";  ]]]
            - height: 200px
            - font-size: 25px
      - type: vertical-stack
        cards:
          - type: custom:button-card
            color_type: label-card
            color: rgb(44, 109, 214)
            name: Air purifier
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: switch.bedroom
                color_type: card
                name: BED ROOM
                color: rgb(66, 134, 244)
                icon: mdi:air-purifier
              - type: custom:button-card
                entity: switch.office_area
                name: OFFICE
                color_type: card
                color: rgb(66, 134, 244)
                icon: mdi:air-purifier
      - type: custom:weather-card
        entity: weather.home
        current: true
        details: false
        forecast: true
        hourly_forecast: false
        number_of_forecasts: 5
      - type: custom:simple-thermostat
        entity: climate.living_room
      - type: horizontal-stack
        title: BED ROOM
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            entities:
              - sensor.ble_temperature_bed_room_2
            line_color: blue
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            name: Humidity
            entities:
              - sensor.ble_humidity_bed_room
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
      - type: horizontal-stack
        title: OFFICE
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            entities:
              - sensor.ble_temperature_work_room_2
            line_color: blue
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            name: Humidity
            entities:
              - sensor.ble_humidity_work_room
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
      - type: horizontal-stack
        title: LIVING ROOM
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            entities:
              - sensor.ble_temperature_living_room_2
            line_color: blue
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            name: Humidity
            entities:
              - sensor.ble_humidity_living_room
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
  - path: car
    title: Car
    badges: []
    icon: mdi:car-connected
    cards:
      - type: vertical-stack
        cards:
          - type: map
            aspect_ratio: '16:9'
            default_zoom: 13
            entities:
              - device_tracker.tesla_location
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.tesla_battery_level
                name: Battery
              - entity: sensor.tesla_ideal_battery_range_mi
                name: Range
            name: Battery Level
            hours_to_show: 24
            points_per_hour: 2
          - type: custom:bar-card
            width: 70%
            entities:
              - name: Battery
                entity: sensor.tesla_battery_level
              - name: Range
                entity: sensor.tesla_ideal_battery_range_mi
                max: 324
            positions:
              icon: 'off'
              indicator: inside
              name: outside
          - type: custom:mini-graph-card
            name: Temperature
            points_per_hour: 2
            icon: mdi:battery
            entities:
              - entity: sensor.tesla_inside_temp
                name: Inside
              - entity: sensor.tesla_outside_temp
                name: Outside
            line_color: blue
          - type: glance
            entities:
              - entity: binary_sensor.tesla_healthy
                name: Car Health
              - entity: sensor.tesla_state
                name: Car State
              - entity: binary_sensor.tesla_plugged_in
                name: Plugged In
          - type: glance
            entities:
              - entity: binary_sensor.tesla_park_brake
                name: Park Brake
              - entity: binary_sensor.tesla_sentry_mode
                name: Sentry Mode
              - entity: sensor.tesla_speed
                name: Speed
      - type: entities
        entities:
          - entity: sensor.tesla_display_name
            name: Name
          - entity: sensor.tesla_state
            name: Status
          - entity: sensor.tesla_since
            name: Last Status Change
          - entity: binary_sensor.tesla_healthy
            name: Logger Healthy
          - entity: sensor.tesla_version
            name: Software Version
          - entity: binary_sensor.tesla_update_available
            name: Available Update Status
          - entity: sensor.tesla_update_version
            name: Available Update Version
          - entity: sensor.tesla_model
            name: Tesla Model
          - entity: sensor.tesla_trim_badging
            name: Trim Badge
          - entity: sensor.tesla_exterior_color
            name: Exterior Color
          - entity: sensor.tesla_wheel_type
            name: Wheel Type
          - entity: sensor.tesla_spoiler_type
            name: Spoiler Type
          - entity: sensor.tesla_geofence
            name: Geo-fence Name
          - entity: proximity.home_tesla
            name: Distance to Home
          - entity: sensor.tesla_latitude
            name: Latitude
          - entity: sensor.tesla_longitude
            name: Longitude
          - entity: sensor.tesla_shift_state
            name: Shifter State
          - entity: sensor.tesla_speed
            name: Speed
          - entity: sensor.tesla_speed_mph
            name: Speed (MPH)
          - entity: sensor.tesla_heading
            name: Heading
          - entity: sensor.tesla_elevation
            name: Elevation (m)
          - entity: sensor.tesla_elevation_ft
            name: Elevation (ft)
          - entity: binary_sensor.tesla_locked
            name: Locked
          - entity: binary_sensor.tesla_sentry_mode
            name: Sentry Mode Enabled
          - entity: binary_sensor.tesla_windows_open
            name: Windows Open
          - entity: binary_sensor.tesla_doors_open
            name: Doors Open
          - entity: binary_sensor.tesla_trunk_open
            name: Trunk Open
          - entity: binary_sensor.tesla_frunk_open
            name: Frunk Open
          - entity: binary_sensor.tesla_is_user_present
            name: User Present
          - entity: binary_sensor.tesla_is_climate_on
            name: Climate On
          - entity: sensor.tesla_inside_temp
            name: Inside Temperature
          - entity: sensor.tesla_outside_temp
            name: Outside Temperature
          - entity: binary_sensor.tesla_is_preconditioning
            name: Preconditioning
          - entity: sensor.tesla_odometer
            name: Odometer
          - entity: sensor.tesla_odometer_mi
            name: Odometer (miles)
          - entity: sensor.tesla_est_battery_range_km
            name: Battery Range (km)
          - entity: sensor.tesla_est_battery_range_mi
            name: Estimated Battery Range (mi)
          - entity: sensor.tesla_rated_battery_range_km
            name: Rated Battery Range (km)
          - entity: sensor.tesla_rated_battery_range_mi
            name: Rated Battery Range (mi)
          - entity: sensor.tesla_ideal_battery_range_km
            name: Ideal Battery Range (km)
          - entity: sensor.tesla_ideal_battery_range_mi
            name: Ideal Battery Range (mi)
          - entity: sensor.tesla_battery_level
            name: Battery Level
          - entity: sensor.tesla_usable_battery_level
            name: Usable Battery Level
          - entity: binary_sensor.tesla_plugged_in
            name: Plugged In
          - entity: sensor.tesla_charge_energy_added
            name: Charge Energy Added
          - entity: sensor.tesla_charge_limit_soc
            name: Charge Limit
          - entity: binary_sensor.tesla_charge_port_door_open
            name: Charge Port Door Open
          - entity: sensor.tesla_charger_actual_current
            name: Charger Current
          - entity: sensor.tesla_charger_phases
            name: Charger Phases
          - entity: sensor.tesla_charger_power
            name: Charger Power
          - entity: sensor.tesla_charger_voltage
            name: Charger Voltage
          - entity: sensor.tesla_scheduled_charging_start_time
            name: Scheduled Charging Start Time
          - entity: sensor.tesla_time_to_full_charge
            name: Time To Full Charge
          - entity: sensor.tesla_exterior_color
            name: Exterior Color
          - entity: sensor.tesla_wheel_type
            name: Wheel Type
          - entity: sensor.tesla_spoiler_type
            name: Spoiler Type
          - entity: sensor.tesla_geofence
            name: Geo-fence Name
          - entity: proximity.home_tesla
            name: Distance to Home
          - entity: sensor.tesla_latitude
            name: Latitude
          - entity: sensor.tesla_longitude
            name: Longitude
          - entity: sensor.tesla_shift_state
            name: Shifter State
          - entity: sensor.tesla_speed
            name: Speed
          - entity: sensor.tesla_speed_mph
            name: Speed (MPH)
          - entity: sensor.tesla_heading
            name: Heading
          - entity: sensor.tesla_elevation
            name: Elevation (m)
          - entity: sensor.tesla_elevation_ft
            name: Elevation (ft)
          - entity: binary_sensor.tesla_locked
            name: Locked
          - entity: binary_sensor.tesla_sentry_mode
            name: Sentry Mode Enabled
          - entity: binary_sensor.tesla_windows_open
            name: Windows Open
          - entity: binary_sensor.tesla_doors_open
            name: Doors Open
          - entity: binary_sensor.tesla_trunk_open
            name: Trunk Open
          - entity: binary_sensor.tesla_frunk_open
            name: Frunk Open
          - entity: binary_sensor.tesla_is_user_present
            name: User Present
          - entity: binary_sensor.tesla_is_climate_on
            name: Climate On
          - entity: sensor.tesla_inside_temp
            name: Inside Temperature
          - entity: sensor.tesla_outside_temp
            name: Outside Temperature
          - entity: binary_sensor.tesla_is_preconditioning
            name: Preconditioning
          - entity: sensor.tesla_odometer
            name: Odometer
          - entity: sensor.tesla_odometer_mi
            name: Odometer (miles)
          - entity: sensor.tesla_est_battery_range_km
            name: Battery Range (km)
          - entity: sensor.tesla_est_battery_range_mi
            name: Estimated Battery Range (mi)
          - entity: sensor.tesla_rated_battery_range_km
            name: Rated Battery Range (km)
          - entity: sensor.tesla_rated_battery_range_mi
            name: Rated Battery Range (mi)
          - entity: sensor.tesla_ideal_battery_range_km
            name: Ideal Battery Range (km)
          - entity: sensor.tesla_ideal_battery_range_mi
            name: Ideal Battery Range (mi)
          - entity: sensor.tesla_battery_level
            name: Battery Level
          - entity: sensor.tesla_usable_battery_level
            name: Usable Battery Level
          - entity: binary_sensor.tesla_plugged_in
            name: Plugged In
          - entity: sensor.tesla_charge_energy_added
            name: Charge Energy Added
          - entity: sensor.tesla_charge_limit_soc
            name: Charge Limit
          - entity: binary_sensor.tesla_charge_port_door_open
            name: Charge Port Door Open
          - entity: sensor.tesla_charger_actual_current
            name: Charger Current
          - entity: sensor.tesla_charger_phases
            name: Charger Phases
          - entity: sensor.tesla_charger_power
            name: Charger Power
          - entity: sensor.tesla_charger_voltage
            name: Charger Voltage
          - entity: sensor.tesla_scheduled_charging_start_time
            name: Scheduled Charging Start Time
          - entity: sensor.tesla_time_to_full_charge
            name: Time To Full Charge
  - icon: mdi:server
    badges: []
    cards:
      - type: custom:transmission-card
        hide_type: false
        default_type: active
      - type: custom:vertical-stack-in-card
        title: Frigate Object Detection
        cards:
          - type: glance
            entities:
              - sensor.coral_inference_speed
              - sensor.detection_fps
      - type: picture-entity
        image: https://demo.home-assistant.io/stub_config/bedroom.png
        entity: camera.doorbell
      - type: picture-entity
        image: https://demo.home-assistant.io/stub_config/bedroom.png
        entity: camera.doorbell_person
      - type: picture-entity
        image: https://demo.home-assistant.io/stub_config/bedroom.png
        entity: camera.doorbell_dog
      - type: horizontal-stack
        title: INTERNET
        cards:
          - type: custom:mini-graph-card
            name: Download
            entities:
              - sensor.speedtest_download
            line_color: blue
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            name: Upload
            entities:
              - sensor.speedtest_upload
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            name: Ping
            entities:
              - sensor.speedtest_ping
            line_color: var(--accent-color)
            line_width: 8
            font_size: 75
  - icon: mdi:robot-vacuum
    badges: []
    cards:
      - type: custom:vacuum-card
        entity: vacuum.roomba
        stats:
          default:
            - attribute: filter_left
              unit: hours
              subtitle: Filter
            - attribute: side_brush_left
              unit: hours
              subtitle: Side brush
            - attribute: main_brush_left
              unit: hours
              subtitle: Main brush
            - attribute: sensor_dirty_left
              unit: hours
              subtitle: Sensors
          cleaning:
            - attribute: cleaned_area
              unit: m2
              subtitle: Cleaning area
            - attribute: cleaning_time
              unit: minutes
              subtitle: Cleaning time
        actions:
          - name: Clean living room
            service: script.clean_living_room
            icon: mdi:sofa
          - name: Clean bedroom
            service: script.clean_bedroom
            icon: mdi:bed-empty
          - name: Clean kitchen
            service: script.clean_kitchen
            icon: mdi:silverware-fork-knife
