# !toggle word-wrap
title: ""
swipe_nav:
  wrap: false
  animate: flip
  prevent_default: true
  swipe_amount: 30
views: !include_dir_list lovelace/views/
button_card_templates: !include_dir_merge_named button_card_template/
