# !toggle word-wrap
title: ""
views: !include_dir_list lovelace/views/
background: "var(--background-image)"
button_card_templates: !include_dir_merge_named "custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"