# !toggle word-wrap
title: ""
button_card_templates: !include_dir_merge_named "lovelace/rounded-templates"
views: !include_dir_list lovelace/views/
background: "var(--background-image)"
decluttering_templates: !include_dir_merge_named lovelace/decluttering-templates