# !toggle word-wrap
title: ""
swipe_nav:
  wrap: false
  animate: flip
  prevent_default: true
  swipe_amount: 30
button_card_templates: !include_dir_merge_named minimalist-templates/
views: !include_dir_list lovelace/views/
background: "var(--background-image)"
decluttering_templates: !include_dir_merge_named lovelace/decluttering