- platform: mqtt
  state_topic: "sds011-mqtt/air-quality/master-2-pi4"
  unit_of_measurement: "μg/m³"
  icon: "mdi:weather-fog"
  value_template: '{{value_json.PM10 | float}}'
  name: 'Master PI 4 Air Quality PM 10'
  unique_id: 'master-2-pi4:air-quality-pm-10'

- platform: mqtt
  state_topic: "sds011-mqtt/air-quality/master-2-pi4"
  unit_of_measurement: "μg/m³"
  icon: "mdi:weather-fog"
  value_template: '{{value_json.PM25 | float}}'
  name: 'Master PI-4 Air Quality PM 2.5'
  unique_id: 'master-2-pi4:air-quality-pm-2.5'

- platform: mqtt
  state_topic: "sds011-mqtt/air-quality/pi3-host"
  unit_of_measurement: "μg/m³"
  icon: "mdi:weather-fog"
  value_template: '{{value_json.PM10 | float}}'
  name: 'PI-3 Host Air Quality PM 10'
  unique_id: 'pi3-host:air-quality-pm-10'

- platform: mqtt
  state_topic: "sds011-mqtt/air-quality/pi3-host"
  unit_of_measurement: "μg/m³"
  icon: "mdi:weather-fog"
  value_template: '{{value_json.PM25 | float}}'
  name: 'PI-3 Host Air Quality PM 2.5'
  unique_id: 'pi3-host:air-quality-pm-2.5'