- platform: mqtt
  state_topic: "sds011-mqtt/air-quality/k8s-3-hp-4590t"
  unit_of_measurement: "μg/m³"
  icon: "mdi:weather-fog"
  value_template: '{{value_json.PM10 | float}}'
  name: 'Living room Air Quality PM 10'
  unique_id: 'livingroom:air-quality-pm-10'

- platform: mqtt
  state_topic: "sds011-mqtt/air-quality/k8s-3-hp-4590t"
  unit_of_measurement: "μg/m³"
  icon: "mdi:weather-fog"
  value_template: '{{value_json.PM25 | float}}'
  name: 'Living room Air Quality PM 2.5'
  unique_id: 'livingroom:air-quality-pm-2.5'
