
- platform: plex_recently_added
  name: Recently Added Movies # will create sensor.recently_added_movies
  token: !secret plex_token
  host: !secret plex_host
  port: 32400

- platform: sonarr_upcoming_media
  api_key: !secret sonarr_apikey
  host: sonarr
  port: 8989
  days: 7
  ssl: false
  max: 10