
- platform: plex_recently_added
  token: !secret plex_token
  host: 192.168.20.104
  port: 32400

- platform: sonarr_upcoming_media
  api_key: !secret sonarr_apikey
  host: sonarr
  port: 8989
  days: 7
  ssl: false
  max: 10

- platform: scrape
  name: synology_dsm_latest
  resource: https://www.synology.com/en-global/releaseNote/DSM
  select: >
    #release_notes_content > div:first-child > h3
  value_template: >
    {{ value.split(' ')[1] }}
  scan_interval: 86400