- platform: template
  sensors:
    ble_temperature_bed_room:
      friendly_name : "Bed Room Temp F"
      value_template: >-
        {% set t = states('sensor.ble_temperature_bed_room_2') | float(0) %}
        {{((t)*9/5)+32}}
      unit_of_measurement: "F"

    ble_temperature_work_room:
      friendly_name : "Work Room Temp F"
      value_template: >-
        {% set t = states('sensor.ble_temperature_work_room_2') | float(0) %}
        {{((t)*9/5)+32}}
      unit_of_measurement: "F"

    ble_temperature_living_room:
      friendly_name : "Living Room Temp F"
      value_template: >-
        {% set t = states('sensor.ble_temperature_living_room_2') | float(0) %}
        {{((t)*9/5)+32}}
      unit_of_measurement: "F"

    office_lights_automation_blocker:
      value_template: >-
        {% if now().weekday() in (0,1,2,3,4) and now().hour < 17 and now().hour >= 8 -%}
          on
        {%- else -%}
          off
        {%- endif %}

    outside_temperature:
      friendly_name : "Outside Temperature"
      value_template: '{{ states.weather.home.attributes.temperature }}'
    
    presence_distance:
      friendly_name : "Presence Distance"
      value_template: '{{ states.sensor.vpogu_pixel_6_room_presence.attributes.distance }}'
