sensor:      
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'

  - platform: template
    sensors:
      tesla_est_battery_range_mi:
        friendly_name: Estimated Range (mi)
        unit_of_measurement: mi
        icon_template: mdi:gauge
        availability_template: "{{ has_value('sensor.tesla_est_battery_range_km') }}"
        value_template: >
          {% if has_value('sensor.tesla_est_battery_range_km') %}
            {{ (states('sensor.tesla_est_battery_range_km') | float / 1.609344) | round(2) }}
          {% endif %}

      tesla_rated_battery_range_mi:
        friendly_name: Rated Range (mi)
        unit_of_measurement: mi
        icon_template: mdi:gauge
        availability_template: "{{ has_value('sensor.tesla_rated_battery_range_km') }}"
        value_template: >
          {% if has_value('sensor.tesla_rated_battery_range_km') %}
            {{ (states('sensor.tesla_rated_battery_range_km') | float / 1.609344) | round(2) }}
          {% endif %}

      tesla_ideal_battery_range_mi:
        friendly_name: Ideal Range (mi)
        unit_of_measurement: mi
        icon_template: mdi:gauge
        availability_template: "{{ has_value('sensor.tesla_ideal_battery_range_km') }}"
        value_template: >
          {% if has_value('sensor.tesla_ideal_battery_range_km') %}
            {{ (states('sensor.tesla_ideal_battery_range_km') | float / 1.609344) | round(2) }}
          {% endif %}

      tesla_odometer_mi:
        friendly_name: Odometer (mi)
        unit_of_measurement: mi
        icon_template: mdi:counter
        availability_template: "{{ has_value('sensor.tesla_odometer') }}"
        value_template: >
          {% if has_value('sensor.tesla_odometer') %}
            {{ (states('sensor.tesla_odometer') | float / 1.609344) | round(2) }}
          {% endif %}

      tesla_speed_mph:
        friendly_name: Speed (MPH)
        unit_of_measurement: mph
        icon_template: mdi:speedometer
        availability_template: "{{ has_value('sensor.tesla_speed') }}"
        value_template: >
          {% if has_value('sensor.tesla_speed') %}
            {{ (states('sensor.tesla_speed') | float / 1.609344) | round(2) }}
          {% endif %}

      tesla_elevation_ft:
        friendly_name: Elevation (ft)
        unit_of_measurement: ft
        icon_template: mdi:image-filter-hdr
        availability_template: "{{ has_value('sensor.tesla_elevation') }}"
        value_template: >
          {% if has_value('sensor.tesla_elevation') %}
            {{ (states('sensor.tesla_elevation') | float * 3.2808) | round(2) }}
          {% endif %}

      tesla_tpms_pressure_fl_psi:
        friendly_name: Front Left Tire Pressure (psi)
        unit_of_measurement: psi
        icon_template: mdi:car-tire-alert
        availability_template: "{{ has_value('sensor.tesla_tpms_fl') }}"
        value_template: >
          {% if has_value('sensor.tesla_tpms_fl') %}
            {{ (states('sensor.tesla_tpms_fl') | float * 14.50377) | round(2) }}
          {% endif %}

      tesla_tpms_pressure_fr_psi:
        friendly_name: Front Right Tire Pressure (psi)
        unit_of_measurement: psi
        icon_template: mdi:car-tire-alert
        availability_template: "{{ has_value('sensor.tesla_tpms_fr') }}"
        value_template: >
          {% if has_value('sensor.tesla_tpms_fr') %}
            {{ (states('sensor.tesla_tpms_fr') | float * 14.50377) | round(2) }}
          {% endif %}

      tesla_tpms_pressure_rl_psi:
        friendly_name: Rear Left Tire Pressure (psi)
        unit_of_measurement: psi
        icon_template: mdi:car-tire-alert
        availability_template: "{{ has_value('sensor.tesla_tpms_rl') }}"
        value_template: >
          {% if has_value('sensor.tesla_tpms_rl') %}
            {{ (states('sensor.tesla_tpms_rl') | float * 14.50377) | round(2) }}
          {% endif %}

      tesla_tpms_pressure_rr_psi:
        friendly_name: Rear Right Tire Pressure (psi)
        unit_of_measurement: psi
        icon_template: mdi:car-tire-alert
        availability_template: "{{ has_value('sensor.tesla_tpms_rr') }}"
        value_template: >
          {% if has_value('sensor.tesla_tpms_rr') %}
            {{ (states('sensor.tesla_tpms_rr') | float * 14.50377) | round(2) }}
          {% endif %}

      tesla_active_route_distance_to_arrival_km:
        friendly_name: Active route distance to arrival (km)
        unit_of_measurement: km
        icon_template: mdi:map-marker-distance
        availability_template: "{{ has_value('sensor.tesla_active_route_distance_to_arrival_mi') }}"
        value_template: >
          {% if has_value('sensor.tesla_active_route_distance_to_arrival_mi') %}
            {{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}
          {% endif %}